name: Pyinstaller build
run-name: ${{ github.actor }} is building Executable
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build executable
        uses: CorvusKnight09/Pyinstaller-Windows-Action
        with:
          main: main.py
          artifact: YahtzeeCalc
          icon: icon.ico