name: Pyinstaller build
run-name: ${{ github.actor }} is building Executable
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pyinstaller build
        uses: vednig/pyinstaller-action-windows@v0.1.5
        with:
          # Directory containing source code (optional requirements.txt).
          path: src
          # Specify a file path for requirements.txt file
          requirements: requirements.txt
      
      - uses: actions/upload-artifact@v4
        with:
          name: YahtzeeCalc.exe
          path: src/dist
